FROM ubuntu:16.04

MAINTAINER Matt Renner <matt@hell.co.nz>

RUN apt-get update && apt-get -y upgrade && apt-get install -y \
    wget \
    nginx \
    supervisor \
    curl \
    git \
    php7.0 \
    php7.0-fpm \
	php7.0-curl \
	php7.0-json \
	php7.0-cgi \
	php7.0-imap \
	php7.0-mysql \
	php7.0-pgsql \
	php7.0-mcrypt \
	php7.0-mbstring \ 
	php7.0-opcache \
	php7.0-bcmath \
	php7.0-readline \
	php7.0-zip \
	php7.0-xml \
	php-pear \
	php-dev \
	nano \
	mtr \
	net-tools \
	iputils-ping

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php --install-dir=/bin --filename=composer
RUN php -r "unlink('composer-setup.php');"

ADD conf/supervisord.conf /etc/supervisord.conf

# Copy our PHP conf
RUN mkdir -p /var/run/php
RUN mkdir -p /var/log/php

RUN rm -Rf /etc/php/7.0/fpm/php-fpm.conf
RUN rm -Rf /etc/php/7.0/fpm/pool.d/*

ADD conf/php/php-fpm.conf /etc/php/7.0/fpm/php-fpm.conf
ADD conf/php/pools/*.conf /etc/php/7.0/fpm/pool.d/

# Copy our nginx config
RUN rm -Rf /etc/nginx/nginx.conf
ADD conf/nginx/nginx.conf /etc/nginx/nginx.conf
ADD conf/nginx/sites-enabled/*.conf /etc/nginx/sites-enabled/

VOLUME ["/var/www"]

EXPOSE 80

ADD docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh
CMD ["/docker-entrypoint.sh"]