version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./docker/mysql:/var/lib/mysql
    restart: always
    command: docker-entrypoint.sh --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password123

  api:
    build: ./docker/php-web
    restart: always
    volumes:
       - ./:/var/www
    ports:
      - "80:80"
    links:
      - db
